name: Check Sections

on: [push, pull_request]

jobs:
  check-sections:
    strategy:
      matrix:
        document:
          - 'entrust'
        include:
          - source: 'rfc3647'
          - document: 'entrust'
            source: 'tlsbr'

    name: Check sections of ${{ matrix.document }} against ${{ matrix.source }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check sections
      run: |
        python tools/check-sections.py ${{ matrix.document }}.md ${{ matrix.source }} > output.txt

    - name: Compare sections
      run: |
        if ! diff -u tests/expected/${{ matrix.document }}-${{ matrix.source }}-sections.txt output.txt; then
          echo "Sections have changed, please verify the diff above and fix or commit changes"
          exit 1
        fi
