name: Test tools
on:
  push:
    branches: ["main"]
    paths:
      - "tools/**"
  pull_request:
    paths:
      - "tools/**"

jobs:
  test-tools-job:
    name: Run Unit Tests for Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Execute Unit Tests
        run: |
          cd ./tools
          python -m unittest *_test.py
